version: '3.8'
services:
  postgres-server:
    image: postgres:16
    container_name: zabbix-postgres
    networks:
      - zabbix-net
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: 7OInJJx3wNgDZLT
      POSTGRES_DB: zabbix
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.2.10-ubuntu
    container_name: zabbix-server
    networks:
      - zabbix-net
    depends_on:
      - postgres-server
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: 7OInJJx3wNgDZLT
      POSTGRES_DB: zabbix
      ZBX_STARTPOLLERS: 8
      ZBX_REMOTECOMMANDS: "1"
      ZBX_TIMEOUT: "30"
      ZBX_STARTIPMIPOLLERS: "1"
      #ZBX_STARTJAVAPOLLERS: "1"
      ZBX_STARTSNMPTRAPPER: "1"
      ZBX_STARTVMWARECOLLECTORS: "1"
      ZBX_STARTREPORTWRITERS: "1"
      ZBX_STARTREPORTMANAGERS: "1"
      ZBX_STARTCONNECTORS: "1"
      ZBX_STARTCONNECTORWORKERS: "1"
      ZBX_STARTCONNECTORMANAGERS: "1"
      ZBX_JAVAGATEWAY: "zabbix-java-gateway"
      ZBX_JAVAGATEWAYPORT: "10052"
      ZBX_STARTJAVAPOLLERS: "0"         # Отключено по умолчанию
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:7.2.10-ubuntu
    container_name: zabbix-web
    networks:
      - zabbix-net
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: 7OInJJx3wNgDZLT
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Moscow"
      ZBX_SERVER_NAME: "Zabbix Monitoring"
      ENABLE_WEB_ACCESS_LOG: "true"
    volumes:
      - ./ssl:/etc/ssl/nginx
      - ./nginx.conf:/etc/nginx/conf.d/zabbix.conf
    restart: unless-stopped
  zabbix-agent:
    image: zabbix/zabbix-agent:7.2.10-ubuntu
    container_name: zabbix-agent
    networks:
      - zabbix-net
    environment:
      ZBX_HOSTNAME: zabbix.geekslore.ru
      ZBX_SERVER_HOST: zabbix.geekslore.ru
      ZBX_ACTIVE_ALLOW: "true"
    restart: unless-stopped
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:7.2.10-ubuntu
    container_name: zabbix-java-gateway
    networks:
      - zabbix-net
    restart: unless-stopped
networks:
  zabbix-net:
    driver: bridge

volumes:
  postgres-data:
