services:
  my_awesome_mysql:
    build:
      context: .
      dockerfile: Dockerfiledb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: userpassword
    hostname: my-my-awesome-mysql
    container_name: my-awesome-mysql
    ports: -
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-uroot", "-prootpass"]
    #   interval: 10s
    #   timeout: 15s
    #   retries: 5
    networks:
      - frontend

  my_awesome_wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      #jj
    #image: phpmyadmin:5.2.0-apache
    hostname: my-my_awesome-wordpress
    container_name: my-awesome-wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    #
    extra_hosts:
      - "host-gateway:localhost"
    networks:
       - frontend
    # depends_on:
    #   - mydb
    #    condition: service_healthy
networks:
  frontend:
    name: my-awesome-network
    labels:
      - "network=Custom"
volumes:
  mysql:
  wordpress:
