
FROM wordpress:latest
#RUN rm /var/www/html/wp-config.php
COPY wp-config.php /usr/src/wordpress/
RUN chown www-data:www-data  /usr/src/wordpress/wp-config.php
 #/var/www/html
#CMD cp /usr/src/wordpress/wp-config.php /var/www/html
