
version: '3'
services:
  my-awesome-database:
    build:
      context: .
      dockerfile: Dockerfiledb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: userpassword
    hostname: my-awesome-database
    container_name: my-awesome-database
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-uroot", "-prootpass"]
    #   interval: 10s
    #   timeout: 15s
    #   retries: 5
    networks:
      - frontend

  my-awesome-wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      #jj
    #image: phpmyadmin:5.2.0-apache
    hostname: my-my_awesome-wordpress
    container_name: my-awesome-wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: my-awesome-mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

    volumes:
      - wordpress:/var/www/html
    #
    # extra_hosts:
    #   - "localhost:host-gateway"
    networks:
       - frontend
    depends_on:
      - my-awesome-database
       #condition: service_healthy
networks:
  frontend:
    name: my-awesome-network
    labels:
      - "network=Custom"
volumes:
  mysql:
    name: mysql
  wordpress:
    name: wordpress
